refresh_rate: 2 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/tui.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - requests
# loggers:
#   app::backend::db:
#     level: info
#   app::requests:
#     level: info
#     appenders:
#       - requests
#     additive: false
